# -*- coding: utf-8 -*-
"""ASSIGNMENT 2: Module 3: Control Structures in Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cmen_2a20uGeCdh1sd24O7vdk1GdUv1E
"""

# Taking input from the user and converting it to integer
number = int(input("Enter a number: "))

# Checking whether the number is even or odd
if number % 2 == 0:
    print(str(number) + " is an Even Number")
else:
    print(str(number) + " is an Odd Number")

sum=0
for i in range(1,51):
  sum=sum+i
print("The sum of number from 1 to 50 is:",sum)